#!/usr/bin/env bash
#
while IFS=":" read username password userid groupid useridinfo homedir command
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $command. $userid place is protected by the passcode $password, more info about the user here: $useridinfo"
done < /etc/passwd
