#!/usr/bin/env bash
# While loops; iteration 4 displays bad luck, iteration 8 displays good luck, everything else displays Best School
x=1
while [ $x -le 10 ]
do
	if [ $x == 4 ]
	then
		echo bad luck
	elif [ $x == 8 ]
	then
		echo good luck
	else
		echo Best School
	fi
done
