#!/usr/bin/env bash
# While loop using case
x=1
while [ $x -le 20 ]
do
	echo $x
	read $x
	case $x in
		4)
			echo bad luck from China;;
		9)
			echo bad luck from Japan;;
		17)
			echo bad luck from Italy;;
	esac
	_=$((x++))
done
