#!/usr/bin/env bash
# Using While loop displaying 12 hours and 59 minutes
hour=0
while [ $hour -le 12 ]
do
	echo Hour: $hour
	min=1
	while [ $min -le 59 ]
	do
		echo $min
		_=$((min++))
	done
	_=$((hour++))
done
