#!/usr/bin/env bash
# Using While loop displaying 12 hours and 59 minutes
min=0
hour=0
echo Hour: $hour
while [ $min -le 60 ]
do
	_=$((min++))
	if [ $min == 60 ]
	then
		_=$((hour++))
		echo Hour: $hour
		min=1
		echo $min
	else
		echo $min
	fi
done
