#!/usr/bin/env bash
#
if $school -e
then
	echo school file exists
	if $school -empty
	then
		echo school file is empty
	elif $school ! -empty
	then
		echo school file is not empty
	else
		echo school is a regular file
	fi
else
	echo school file does not exist
fi
