#!/usr/bin/env bash
#
if [ -e "school" ] == true
then
	echo school file exists
	if [ -s "school" ]
	then
		echo school file is empty
	elif [ -s "school" ]
	then
		echo school file is not empty
	else
		echo school is a regular file
	fi
else
	echo school file does not exist
fi
