#!/usr/bin/env bash
#
# /etc/init.d/11-manage_my_process

start() {
	./manage_my_process &
}

stop() {
	pkill -f ./manage_my_process	
}

case "$1" in
	start)
		start
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started";;
	stop)
		stop
		sudo rm my_process.pid
		echo "manage_my_process stopped";;
	restart)
		stop
		sudo rm my_process.pid
		start
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted";;
	*)
		echo "Usage: manage_my_process {start|stop|restart}";;
	esac
