#!/usr/bin/env bash
#
# /etc/init.d/11-manage_my_process

file="/var/run/my_process.pid"

function start() {
	(./manage_my_process) &
	echo $$ > $file
	echo "manage_my_process started"
}

function stop() {
	pkill -f $file
	sudo rm $file
	echo "manage_my_process stopped"
}

function restart() {
	pkill -f $file
	sudo rm $file
	(./manage_my_process) &
	echo $$ > $file
	echo "manage_my_process restarted"
}
case "$1" in
	"start")
		start
		;;
	"stop")
		stop
		;;
	"restart")
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
	esac
